import type { ExpoConfig, ConfigContext } from "expo/config";
import {
  APP_NAME,
  APP_SLUG,
  APP_SCHEME,
  IOS_BUNDLE_ID,
  ANDROID_PACKAGE,
} from "./src/config/app";

/**
 * All native identity (name, bundle id, scheme) is derived from the single
 * config constant in src/config/app.ts so there is exactly one place to
 * rename the product.
 */
export default ({ config }: ConfigContext): ExpoConfig => ({
  ...config,
  name: APP_NAME,
  slug: APP_SLUG,
  scheme: APP_SCHEME,
  version: "1.0.0",
  orientation: "portrait",
  icon: "./assets/icon.png",
  userInterfaceStyle: "automatic",
  splash: {
    image: "./assets/splash.png",
    resizeMode: "contain",
    backgroundColor: "#FBF7F4",
  },
  assetBundlePatterns: ["**/*"],
  ios: {
    supportsTablet: true,
    bundleIdentifier: IOS_BUNDLE_ID,
    privacyManifests: {
      NSPrivacyAccessedAPITypes: [
        {
          NSPrivacyAccessedAPIType: "NSPrivacyAccessedAPICategoryUserDefaults",
          NSPrivacyAccessedAPITypeReasons: ["CA92.1"],
        },
        {
          NSPrivacyAccessedAPIType: "NSPrivacyAccessedAPICategoryFileTimestamp",
          NSPrivacyAccessedAPITypeReasons: ["C617.1"],
        },
      ],
      NSPrivacyCollectedDataTypes: [],
      NSPrivacyTracking: false,
    },
    infoPlist: {
      // Literal "$(KEY)" placeholders, per Apple's InfoPlist.strings
      // localization mechanism: iOS looks up NSPhotoLibraryUsageDescription
      // in the active-language en.lproj/fr.lproj/ar.lproj/InfoPlist.strings
      // at runtime. Those per-locale files are generated by the config
      // plugin in plugins/withLocalizedPermissions.js (sourced from
      // store/permissions-l10n.json) during `expo prebuild` — do not
      // replace these with literal English text, that would bypass
      // localization entirely.
      NSPhotoLibraryUsageDescription: "$(NSPhotoLibraryUsageDescription)",
      NSCameraUsageDescription: "$(NSCameraUsageDescription)",
      ITSAppUsesNonExemptEncryption: false,
    },
  },
  android: {
    package: ANDROID_PACKAGE,
    adaptiveIcon: {
      foregroundImage: "./assets/adaptive-icon-foreground.png",
      backgroundColor: "#FBF7F4",
    },
    permissions: ["READ_MEDIA_IMAGES", "CAMERA"],
  },
  web: {
    bundler: "metro",
    output: "single",
    favicon: "./assets/favicon.png",
  },
  plugins: [
    "expo-router",
    "expo-sqlite",
    "expo-updates",
    // expo-image-picker's own plugin is intentionally given no
    // photosPermission/cameraPermission options: passing literal text there
    // would overwrite the "$(KEY)" placeholders set above in ios.infoPlist
    // and silently defeat the InfoPlist.strings localization plugin.
    "expo-image-picker",
    "./plugins/withLocalizedPermissions.js",
    [
      "sentry-expo",
      {
        organization: process.env.SENTRY_ORG ?? "",
        project: process.env.SENTRY_PROJECT ?? "",
      },
    ],
  ],
  experiments: {
    typedRoutes: true,
  },
  updates: {
    url: process.env.EAS_UPDATE_URL ?? undefined,
    fallbackToCacheTimeout: 0,
  },
  runtimeVersion: {
    policy: "appVersion",
  },
  extra: {
    eas: {
      projectId: process.env.EAS_PROJECT_ID ?? "00000000-0000-0000-0000-000000000000",
    },
  },
});
