import type { ExpoConfig, ConfigContext } from "expo/config";

/**
 * These five values are intentionally literal, not imported from
 * src/config/app.json (the single source of truth every app screen reads).
 * Node's config-loading step for app.config.ts has proven unable to reliably
 * resolve *any* cross-file import for these values across different Expo
 * CLI/Node/build-image combinations — a plain `.ts` import failed with
 * "Cannot use import statement outside a module", and a `.json` import
 * failed with 'needs an import attribute of "type: json"' on a newer image.
 * A self-contained app.config.ts has no such failure mode. Drift between
 * these literals and src/config/app.json is caught by
 * __tests__/appConfig.test.ts, not by a runtime import.
 */
const APP_NAME = "The Nursing Queen";
const APP_SLUG = "the-nursing-queen";
const APP_SCHEME = "nursingqueen";
const IOS_BUNDLE_ID = "com.nursingqueen.app";
const ANDROID_PACKAGE = "com.nursingqueen.app";
export default ({ config }: ConfigContext): ExpoConfig => ({
  ...config,
  name: APP_NAME,
  slug: APP_SLUG,
  scheme: APP_SCHEME,
  version: "1.0.0",
  orientation: "portrait",
  icon: "./assets/icon.png",
  userInterfaceStyle: "automatic",
  splash: {
    image: "./assets/splash.png",
    resizeMode: "contain",
    backgroundColor: "#FBF7F4",
  },
  assetBundlePatterns: ["**/*"],
  ios: {
    supportsTablet: true,
    bundleIdentifier: IOS_BUNDLE_ID,
    privacyManifests: {
      NSPrivacyAccessedAPITypes: [
        {
          NSPrivacyAccessedAPIType: "NSPrivacyAccessedAPICategoryUserDefaults",
          NSPrivacyAccessedAPITypeReasons: ["CA92.1"],
        },
        {
          NSPrivacyAccessedAPIType: "NSPrivacyAccessedAPICategoryFileTimestamp",
          NSPrivacyAccessedAPITypeReasons: ["C617.1"],
        },
      ],
      NSPrivacyCollectedDataTypes: [],
      NSPrivacyTracking: false,
    },
    infoPlist: {
      // Literal "$(KEY)" placeholders, per Apple's InfoPlist.strings
      // localization mechanism: iOS looks up NSPhotoLibraryUsageDescription
      // in the active-language en.lproj/fr.lproj/ar.lproj/InfoPlist.strings
      // at runtime. Those per-locale files are generated by the config
      // plugin in plugins/withLocalizedPermissions.js (sourced from
      // store/permissions-l10n.json) during `expo prebuild` — do not
      // replace these with literal English text, that would bypass
      // localization entirely.
      NSPhotoLibraryUsageDescription: "$(NSPhotoLibraryUsageDescription)",
      NSCameraUsageDescription: "$(NSCameraUsageDescription)",
      ITSAppUsesNonExemptEncryption: false,
    },
  },
  android: {
    package: ANDROID_PACKAGE,
    adaptiveIcon: {
      foregroundImage: "./assets/adaptive-icon-foreground.png",
      backgroundColor: "#FBF7F4",
    },
    permissions: ["READ_MEDIA_IMAGES", "CAMERA"],
  },
  web: {
    bundler: "metro",
    output: "single",
    favicon: "./assets/favicon.png",
  },
  plugins: [
    "expo-router",
    "expo-sqlite",
    "expo-updates",
    // expo-image-picker's own plugin is intentionally given no
    // photosPermission/cameraPermission options: passing literal text there
    // would overwrite the "$(KEY)" placeholders set above in ios.infoPlist
    // and silently defeat the InfoPlist.strings localization plugin.
    "expo-image-picker",
    "./plugins/withLocalizedPermissions.js",
    [
      "sentry-expo",
      {
        organization: process.env.SENTRY_ORG ?? "",
        project: process.env.SENTRY_PROJECT ?? "",
      },
    ],
  ],
  experiments: {
    typedRoutes: true,
  },
  updates: {
    url: process.env.EAS_UPDATE_URL ?? undefined,
    fallbackToCacheTimeout: 0,
  },
  runtimeVersion: {
    policy: "appVersion",
  },
  extra: {
    eas: {
      projectId: process.env.EAS_PROJECT_ID ?? "00000000-0000-0000-0000-000000000000",
    },
  },
});
